apiVersion: v1
kind: Pod
metadata:
  name: ansible
  namespace: default
spec:
  containers:
  - name: ansible
    image: yourdockerhubuser/manual-ansible:v1
    imagePullPolicy: Always
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
